Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -14,18 +14,25 @@ pipeline {
             }
         }
 
+        stage('Build Docker Image') {
+            steps {
+                echo "Building Docker image..."
+                script {
+                    sh 'docker build -t ${DOCKER_IMAGE} .'
+                }
+            }
+        }
+
         stage('Run Docker Container') {
             steps {
                 echo "Running Docker container..."
                 script {
                     sh '''
-                    # Stop and remove existing container if it exists
                     docker stop ${DOCKER_CONTAINER} || true
                     docker rm ${DOCKER_CONTAINER} || true
-
-                    # Run new container
                     docker run -d --name ${DOCKER_CONTAINER} -p 8000:8000 ${DOCKER_IMAGE} || {
-                        echo "Docker run failed! Exiting..."
+                        echo "Docker run failed! Showing logs:"
+                        docker logs ${DOCKER_CONTAINER} || true
                         exit 1
                     }
                     '''
