Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -31,7 +31,10 @@ pipeline {
                     fi
 
                     echo "=== Starting Docker Build ==="
-                    docker build -t ${DOCKER_IMAGE} .
+                    docker build -t ${DOCKER_IMAGE} . || {
+                        echo "Docker build failed! Exiting..."
+                        exit 1
+                    }
                     '''
                 }
             }
@@ -47,7 +50,10 @@ pipeline {
                     docker rm ${DOCKER_CONTAINER} || true
 
                     # Run new container
-                    docker run -d --name ${DOCKER_CONTAINER} -p 8000:8000 ${DOCKER_IMAGE}
+                    docker run -d --name ${DOCKER_CONTAINER} -p 8000:8000 ${DOCKER_IMAGE} || {
+                        echo "Docker run failed! Exiting..."
+                        exit 1
+                    }
                     '''
                 }
             }
